# Generated by Django 5.2.6 on 2025-09-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='factsStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Facts Start',
                'verbose_name_plural': 'Facts Starts',
            },
        ),
    ]
