# Generated by Django 5.2.6 on 2025-09-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FactsStart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factsstart',
            name='title_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
