# Generated by Django 5.2.6 on 2025-09-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FactsStart', '0002_factsstart_title_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factsstart',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
