# Generated by Django 5.2.6 on 2025-09-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_contact', models.IntegerField(blank=True, max_length=20, null=True)),
                ('email_contact', models.EmailField(blank=True, max_length=25, null=True)),
                ('location_contact', models.CharField(blank=True, max_length=60, null=True)),
                ('iframe_map_contact', models.CharField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Info',
                'verbose_name_plural': 'Infos',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
