# Generated by Django 5.2.6 on 2025-09-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='social_media_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'social media icon',
                'verbose_name_plural': 'social media icons',
            },
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'managed': True, 'verbose_name': 'Info', 'verbose_name_plural': 'Info'},
        ),
    ]
