# Generated by Django 5.2.6 on 2025-09-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_social_media_info_alter_info_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='location_contact_ar',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
