# Generated by Django 5.2.6 on 2025-09-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_info_location_contact_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='phone_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
