# Generated by Django 5.2.6 on 2025-09-20 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category Service',
                'verbose_name_plural': 'Category Services',
            },
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='details',
        ),
        migrations.RemoveField(
            model_name='serviceitem',
            name='name',
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='service_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='service_details_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='service_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='service_name_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicestart',
            name='description_ar',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicestart',
            name='title_ar',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='service_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='services.category_service'),
        ),
    ]
