# Generated by Django 5.2.6 on 2025-09-20 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_ar',
            options={'verbose_name': 'About AR', 'verbose_name_plural': 'Abouts AR'},
        ),
        migrations.AlterModelOptions(
            name='detailssmall_ar',
            options={'verbose_name': 'Detail AR', 'verbose_name_plural': 'Details AR'},
        ),
    ]
