# Generated by Django 5.2.6 on 2025-09-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_item', models.CharField(max_length=200)),
                ('description_item', models.TextField()),
                ('icon_item', models.CharField(max_length=100)),
                ('created_at_item', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feature Item',
                'verbose_name_plural': 'Feature Items',
                'ordering': ['-created_at_item'],
            },
        ),
        migrations.CreateModel(
            name='FeatureStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_Feature', models.CharField(max_length=200)),
                ('description_Feature', models.TextField()),
                ('images_Feature', models.ImageField(upload_to='features/')),
                ('created_at_Feature', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feature Start',
                'verbose_name_plural': 'Feature Starts',
                'ordering': ['-created_at_Feature'],
            },
        ),
    ]
