# Generated by Django 5.2.6 on 2025-09-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeaturesStart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureitem',
            name='description_item_ar',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featureitem',
            name='title_item_ar',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featurestart',
            name='Title_Feature_ar',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featurestart',
            name='description_Feature_ar',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
