# Generated by Django 5.2.6 on 2025-09-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_hero', models.CharField(max_length=200)),
                ('title_hero_ar', models.CharField(max_length=200)),
                ('subtitle_hero', models.CharField(max_length=300)),
                ('subtitle_hero_ar', models.CharField(max_length=300)),
                ('image_hero', models.ImageField(upload_to='hero_images/')),
                ('created_at_hero', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_site', models.CharField(max_length=200)),
                ('title_site_ar', models.CharField(max_length=200)),
                ('logo_site', models.ImageField(upload_to='hero_images/')),
                ('logo_site_ar', models.ImageField(upload_to='hero_images/')),
                ('favicon_site', models.ImageField(upload_to='hero_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Slider',
                'verbose_name_plural': 'Hero Sliders',
            },
        ),
    ]
