# Generated by Django 5.2.6 on 2025-09-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='image_hero_car',
            field=models.ImageField(default='', upload_to='hero_images/'),
            preserve_default=False,
        ),
    ]
