# Generated by Django 5.2.6 on 2025-09-17 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_hero_image_hero_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='image_hero',
        ),
    ]
